title: Which Github-theme defines me as a person?
author: xelune
email: antonia.mattausch@icloud.com
description: > # this means to ignore newlines until "baseurl:"

Does anyone of you know Tyler Durden?

# social links
github_username:  xelune # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
